[versions]
agp = "8.13.2"
xposed = "82"
dexkit = "2.2.0"
kotlin = "2.2.0"

[libraries]
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }