plugins {
	alias(libs.plugins.android.application)
}

android {
	namespace 'cum.wrongchao.v2vpn'
	compileSdk {
		version = release(36)
	}

	defaultConfig {
		applicationId "cum.wrongchao.v2vpn"
		minSdk 26
		targetSdk 37
		versionCode 1
		versionName "1.0"
	}

	buildTypes {
		release {
			minifyEnabled true
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
}

dependencies {
	compileOnly libs.xposed
	implementation libs.kotlin
	implementation libs.dexkit
}